"""
cam/llm_narrator.py
─────────────────────────────────────────────────────────────────────────────
LLM Narrative Generator for Credit Appraisal Memos.

Uses Grok API (OpenAI-compatible) to generate the PROSE sections of the CAM.
All numbers, tables, and scores come from deterministic modules —
the LLM only writes the connecting narrative.

CAM Sections generated here:
  1. Executive Summary        (decision rationale + key risks in 3 sentences)
  2. Company Background       (sector context + promoter profile)
  3. Financial Analysis       (trend narrative — improving/deteriorating)
  4. Risk Factors & Mitigants (structured risk register with mitigants)
  5. Recommendation           (final credit recommendation paragraph)

Sections NOT generated by LLM (populated by doc_builder.py from data):
  - Cover page (pure data)
  - Financial tables (deterministic)
  - Five Cs scorecard table (deterministic)
  - Loan terms table (deterministic)
  - Audit trail (deterministic)

DEMO FALLBACK: If Grok API is unavailable, every section has a
deterministic template that produces sensible output from the data alone.
─────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# ── API Client Setup ──────────────────────────────────────────────────────────

_grok_client = None

def _get_client():
    """Lazily initialize the OpenAI client on first use."""
    global _grok_client
    if _grok_client is None:
        try:
            from openai import OpenAI
            from backend.config import LLM_API_KEY, LLM_BASE_URL, LLM_MODEL
            if LLM_API_KEY:
                _grok_client = OpenAI(
                    api_key=LLM_API_KEY,
                    base_url=LLM_BASE_URL,
                )
                logger.info(
                    "LLM client initialized: model=%s, base_url=%s, api_key=%s...",
                    LLM_MODEL, LLM_BASE_URL, LLM_API_KEY[:8] if LLM_API_KEY else "None"
                )
        except Exception as e:
            logger.error("Failed to initialize LLM client: %s (type: %s)", str(e), type(e).__name__)
    return _grok_client


# ── Output Structure ──────────────────────────────────────────────────────────

@dataclass
class CAMNarrative:
    """All narrative sections of the CAM, ready for doc_builder."""
    executive_summary:   str
    company_background:  str
    financial_analysis:  str
    risk_factors:        str     # Structured as numbered list text
    recommendation:      str
    model_used:          str     # "grok-3" | "template_fallback"
    warnings:            list[str] = field(default_factory=list)


# ── Main Generation Function ──────────────────────────────────────────────────

async def generate_cam_narrative(
    financial_data: dict,
    scorecard:      dict,
    loan_sizing:    dict,
    wc_analysis:    dict,
    rp_analysis:    dict,
    research_cache: dict,
    lit_summary:    dict,
    insights:       dict | None = None,
) -> CAMNarrative:
    """
    Generate all narrative sections for the CAM.
    Tries Grok API first; falls back to deterministic templates.
    """
    ctx = _build_context(
        financial_data, scorecard, loan_sizing,
        wc_analysis, rp_analysis, research_cache, lit_summary, insights
    )

    client = _get_client()
    if client is not None:
        try:
            from backend.config import LLM_MODEL
            logger.info("Generating CAM narrative via Grok API (model=%s)", LLM_MODEL)
            sections = _call_grok_api(ctx)
            return CAMNarrative(model_used=LLM_MODEL, **sections)
        except Exception as e:
            logger.error("Grok API failed: %s (type: %s) — using template fallback", str(e), type(e).__name__)

    logger.info("Generating CAM narrative via deterministic template fallback")
    sections = _template_fallback(ctx)
    warnings = ["Grok API unavailable — narrative generated from deterministic templates"]
    return CAMNarrative(model_used="template_fallback", warnings=warnings, **sections)


# ── Grok API Call ─────────────────────────────────────────────────────────────

def _call_grok_api(ctx: dict) -> dict:
    """
    Call Grok API for all 5 sections in a single well-structured prompt.
    Uses XML tags to extract each section reliably.
    Grok is OpenAI-compatible so we use the openai SDK with x.ai base URL.
    """
    system_prompt = (
        "You are a senior Indian credit analyst with 15+ years of experience "
        "writing Credit Appraisal Memoranda (CAMs) for NBFCs and scheduled commercial banks. "
        "Write in formal, precise banking English using Indian financial conventions: "
        "amounts in lakhs/crores (₹), RBI guidelines, IBC/NCLT references where relevant. "
        "Never invent numbers not provided. Be specific and concise."
    )

    user_prompt = f"""Write a Credit Appraisal Memo narrative for the following case.

Company: {ctx['company_name']}
Sector: {ctx['sector']}
Score: {ctx['score']}/100 | Grade: {ctx['grade']} | Decision: {ctx['decision']}
DSCR: {ctx['dscr']:.2f}x | D/E: {ctx['de_ratio']:.2f}x | Promoter Pledge: {ctx['pledge_pct']:.1f}%
EBITDA Margins (FY2022→FY2024): {ctx['ebitda_margins']}
Revenue CAGR (3yr): {ctx['revenue_cagr']:.1f}%
Litigation Status: {ctx['lit_label']} | Knockout Flag: {ctx['knockout']}
Primary decision trigger: {ctx['primary_trigger']}
Recommended Facility: ₹{ctx['recommended_cr']:.1f} Cr @ {ctx['rate']:.2f}% p.a.
Security Cover: {ctx['security_cover']:.2f}x
Counter-factual: {ctx['counter_factual']}

Generate exactly 5 sections wrapped in XML tags. Each 3–5 sentences. Formal banking tone.
Do not invent figures not given above.

<executive_summary>
(1) Overall credit assessment and grade. (2) Key financial strength. (3) Primary risk or basis for decision.
</executive_summary>

<company_background>
Company business, sector standing, and promoter profile based on data given.
</company_background>

<financial_analysis>
Revenue growth, EBITDA margin trajectory, debt levels, and working capital — cite specific numbers.
</financial_analysis>

<risk_factors>
Write exactly 4 numbered risk factors RELEVANT to this specific case. Format:
1. [Risk Name]: [description]. Mitigant: [mitigant].
2. [Risk Name]: [description]. Mitigant: [mitigant].
3. [Risk Name]: [description]. Mitigant: [mitigant].
4. [Risk Name]: [description]. Mitigant: [mitigant].
IMPORTANT: Only include DSCR risk if DSCR < 1.30x. Only include litigation risk if status is not CLEAN.
Only include promoter pledge risk if pledge > 0%. Do not fabricate risks not supported by the data.
</risk_factors>

<recommendation>
State the credit committee recommendation, decision rationale, key conditions precedent,
and post-sanction monitoring requirements.
</recommendation>"""

    client = _get_client()
    from backend.config import LLM_MODEL
    response = client.chat.completions.create(
        model=LLM_MODEL,
        max_tokens=1500,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
    )

    raw_text = response.choices[0].message.content
    return _parse_xml_response(raw_text)


def _parse_xml_response(text: str) -> dict:
    """Extract sections from the LLM's XML-tagged response."""

    def extract(tag: str) -> str:
        pattern = rf"<{tag}>(.*?)</{tag}>"
        match   = re.search(pattern, text, re.DOTALL)
        return match.group(1).strip() if match else ""

    return {
        "executive_summary":  extract("executive_summary"),
        "company_background": extract("company_background"),
        "financial_analysis": extract("financial_analysis"),
        "risk_factors":       extract("risk_factors"),
        "recommendation":     extract("recommendation"),
    }


# ── Template Fallback ─────────────────────────────────────────────────────────

def _template_fallback(ctx: dict) -> dict:
    """
    Deterministic narrative templates — used when Grok API is unavailable.
    Produces professional, data-accurate text from the context dict.

    FIXES vs previous version:
    - Risk factors are now conditional:
        DSCR risk    → only if dscr < 1.30
        Pledge risk  → only if pledge > 0
        Litigation   → only if lit_label not CLEAN/LOW
    - security_cover reads the actual ratio (e.g. 1.96x), not a score pct
    - revenue_cagr is computed from raw financials if wc_analysis returns 0
    - DSCR sentence uses correct threshold language per case
    """
    c          = ctx["company_name"]
    sec        = ctx["sector"]
    grade      = ctx["grade"]
    score      = ctx["score"]
    dec        = ctx["decision"]
    dscr       = ctx["dscr"]
    de         = ctx["de_ratio"]
    pledge     = ctx["pledge_pct"]
    rec        = ctx["recommended_cr"]
    rate       = ctx["rate"]
    lit        = ctx["lit_label"]
    years      = ctx["years"]
    rev_cagr   = ctx["revenue_cagr"]
    ebitda_m   = ctx["ebitda_margins"]
    trigger    = ctx["primary_trigger"]
    counter    = ctx["counter_factual"]
    promoters  = ctx["promoters"]
    tnw_latest = ctx["tnw_latest"]
    total_debt = ctx["total_debt_latest"]
    sec_cover  = ctx["security_cover"]
    ccc        = ctx["ccc"]

    # ── Executive Summary ─────────────────────────────────────────────────
    if dec == "APPROVE":
        primary_constraint = (
            f"security cover of {sec_cover:.2f}x with adequate collateral backing"
        )
    elif dec == "PARTIAL":
        primary_constraint = (
            f"partial exposure recommended at ₹{rec:.1f} Cr due to: {trigger[:80]}"
        )
    else:
        primary_constraint = trigger[:100] if trigger else "identified risk factors"

    executive_summary = (
        f"{c} has been assigned a credit grade of {grade} ({score}/100) on the "
        f"Five Cs scorecard, resulting in a recommendation to {dec} the proposed "
        f"credit facility. "
        f"The company demonstrates {rev_cagr:.1f}% revenue CAGR over "
        f"{years[0]}–{years[-1]} with EBITDA margins of "
        f"{ebitda_m[0]:.1f}%–{ebitda_m[-1]:.1f}%, supported by tangible net worth "
        f"of ₹{tnw_latest:.0f}L. "
        f"The primary consideration is {primary_constraint}."
    )

    # ── Company Background ────────────────────────────────────────────────
    promo_names = (
        " and ".join(p["name"] for p in promoters) if promoters else "the promoters"
    )
    pledge_line = (
        f"of which {pledge:.1f}% is pledged to lenders as security for existing facilities"
        if pledge > 0
        else "with no shares currently pledged to any lender"
    )

    company_background = (
        f"{c} is a {sec}-sector company promoted by {promo_names}, with operations "
        f"established since its incorporation. "
        f"The promoters hold {ctx['promoter_pct']:.1f}% equity stake, {pledge_line}. "
        f"The company's primary banking relationship is with its existing lenders, "
        f"and it holds an external credit rating from its rating agency."
    )

    # ── Financial Analysis ────────────────────────────────────────────────
    dscr_commentary = (
        f"DSCR of {dscr:.2f}x is below the minimum threshold of 1.30x, "
        f"indicating stressed debt servicing capacity"
        if dscr < 1.30
        else (
            f"DSCR of {dscr:.2f}x comfortably exceeds the minimum threshold of 1.30x, "
            f"indicating adequate debt servicing capacity"
        )
    )
    margin_direction = "improving" if ebitda_m[-1] >= ebitda_m[0] else "declining"

    financial_analysis = (
        f"{c} has grown revenue at a CAGR of {rev_cagr:.1f}% over "
        f"{years[0]}–{years[-1]}, with EBITDA margins {margin_direction} from "
        f"{ebitda_m[0]:.1f}% to {ebitda_m[-1]:.1f}%. "
        f"Total debt stood at ₹{total_debt:.0f}L against tangible net worth of "
        f"₹{tnw_latest:.0f}L, yielding a D/E ratio of {de:.2f}x as at {years[-1]}. "
        f"{dscr_commentary}. "
        f"Working capital intensity reflects a Cash Conversion Cycle of {ccc:.0f} days."
    )

    # ── Risk Factors — conditional on actual case data ────────────────────
    risk_items = []

    # Insights-based risks — add first if insights exist with negative delta
    if ctx.get("has_insights") and ctx.get("insights_delta", 0) < 0:
        insights = ctx.get("insights", {})
        adjustments = insights.get("adjustments", [])
        negative_adjustments = [adj for adj in adjustments if adj.get("delta", 0) < 0]
        if negative_adjustments:
            # Group by pillar for summary
            pillar_impacts = {}
            for adj in negative_adjustments:
                pillar = adj.get("pillar", "")
                delta = adj.get("delta", 0)
                pillar_impacts[pillar] = pillar_impacts.get(pillar, 0) + delta
            
            impact_summary = ", ".join(
                f"{pillar} ({delta:+d} pts)" for pillar, delta in pillar_impacts.items()
            )
            risk_items.append(
                f"Field Intelligence Risk: Analyst observations from site visit identified "
                f"material concerns affecting {impact_summary}. "
                f"Net score impact: {ctx['insights_delta']:+d} pts. "
                f"Mitigant: Enhanced monitoring and quarterly field verification required."
            )

    # Litigation — only if not clean
    if lit not in ("CLEAN", "LOW", ""):
        risk_items.append(
            f"Litigation / Legal Risk ({lit}): {trigger[:120]}. "
            f"Mitigant: {counter[:100]}."
        )

    # DSCR — only if below threshold
    if dscr < 1.30:
        risk_items.append(
            f"Debt Service Risk: DSCR of {dscr:.2f}x is below the minimum threshold "
            f"of 1.30x, leaving limited buffer for revenue or margin stress. "
            f"Mitigant: Proposed escrow of one quarter's debt service as condition precedent."
        )

    # Promoter pledge — only if pledge > 0
    if pledge > 0:
        risk_items.append(
            f"Promoter Pledge Concentration: {pledge:.1f}% of promoter holding is "
            f"pledged, creating margin call risk in the event of stock price decline. "
            f"Mitigant: Pledge release schedule to be agreed as a covenant within 24 months."
        )

    # Working capital — always relevant
    risk_items.append(
        f"Working Capital / Liquidity Risk: Cash Conversion Cycle of {ccc:.0f} days "
        f"indicates elevated debtor and inventory holding relative to payables. "
        f"Mitigant: Monthly stock and debtor statements with drawing power computation."
    )

    # Sector / concentration — always relevant as a fourth item
    risk_items.append(
        f"Sector & Concentration Risk: Exposure to the {sec} sector entails "
        f"susceptibility to input cost volatility, regulatory changes, and customer "
        f"concentration. "
        f"Mitigant: Annual review of sector outlook with customer diversification covenant."
    )

    # Trim to exactly 4 numbered items
    risk_items = risk_items[:4]
    risk_factors = "\n".join(f"{i + 1}. {item}" for i, item in enumerate(risk_items))

    # ── Recommendation ────────────────────────────────────────────────────
    if dec == "REJECT":
        recommendation = (
            f"The Credit Committee is recommended to DECLINE the proposed facility of "
            f"₹{ctx['requested_cr']:.1f} Cr from {c} at this time. "
            f"The primary basis for decline is: {trigger[:120]}. "
            f"The application may be reconsidered subject to: {counter[:150]}. "
            f"No credit facility should be extended until the identified risks are "
            f"fully resolved."
        )
    elif dec == "PARTIAL":
        recommendation = (
            f"The Credit Committee is recommended to consider a PARTIAL approval of "
            f"₹{rec:.1f} Cr (against the requested ₹{ctx['requested_cr']:.1f} Cr) "
            f"@ {rate:.2f}% p.a. for {c} (Grade {grade}), subject to satisfactory "
            f"resolution of pending conditions precedent. "
            f"Disbursement to be withheld pending clearance of: {trigger[:100]}. "
            f"Post-sanction monitoring: quarterly DSCR certification, monthly stock "
            f"statements, and annual pledge reduction milestones."
        )
    else:  # APPROVE
        recommendation = (
            f"The Credit Committee is recommended to APPROVE the facility of "
            f"₹{rec:.1f} Cr @ {rate:.2f}% p.a. for {c} (Grade {grade}). "
            f"The facility is adequately secured with a security cover of "
            f"{sec_cover:.2f}x. "
            f"Conditions precedent: satisfactory legal search, executed security "
            f"documents, and insurance endorsement in lender's favour. "
            f"Post-sanction monitoring: quarterly DSCR review and annual financial audit."
        )

    return {
        "executive_summary":  executive_summary,
        "company_background": company_background,
        "financial_analysis": financial_analysis,
        "risk_factors":       risk_factors,
        "recommendation":     recommendation,
    }


# ── Context Builder ───────────────────────────────────────────────────────────

def _build_context(
    financial_data: dict,
    scorecard:      dict,
    loan_sizing:    dict,
    wc_analysis:    dict,
    rp_analysis:    dict,
    research_cache: dict,
    lit_summary:    dict,
    insights:       dict | None,
) -> dict:
    """Flatten all inputs into a single context dict for prompt / template."""
    fin  = financial_data.get("financials", {})
    pnl  = fin.get("profit_and_loss", {})
    bs   = fin.get("balance_sheet", {})
    comp = financial_data.get("company", {})
    lr   = financial_data.get("loan_request", {})

    def latest(d: dict, key: str, fb=0.0):
        v = d.get(key, fb)
        return float(v[-1]) if isinstance(v, list) and v else float(v or fb)

    def as_float_list(v, fb=0.0):
        if isinstance(v, list):
            return [float(x or fb) for x in v]
        return [fb]

    ebitda_margins = [
        round(m, 1) for m in as_float_list(pnl.get("ebitda_margin_pct", []))
    ]

    # FIX: Revenue CAGR — compute from raw revenues if wc_analysis returns 0
    revenue_cagr = float(wc_analysis.get("revenue_cagr_pct") or 0.0)
    if revenue_cagr == 0.0:
        revenues = as_float_list(pnl.get("revenue", []))
        if len(revenues) >= 2 and revenues[0] > 0:
            n = len(revenues) - 1
            revenue_cagr = round(((revenues[-1] / revenues[0]) ** (1 / n) - 1) * 100, 1)

    # FIX: Security cover — read actual ratio from loan_sizing, not score pct
    security_cover = float(
        loan_sizing.get("security_cover")
        or loan_sizing.get("recommendation", {}).get("security_cover")
        or 0.0
    )
    if security_cover == 0.0:
        # Fallback: compute collateral_limit / recommended_cr
        coll_limit = float(
            loan_sizing.get("collateral_limit_cr")
            or loan_sizing.get("recommendation", {}).get("collateral_limit_cr")
            or 0.0
        )
        rec_cr = float(
            loan_sizing.get("recommendation", {}).get("recommended_cr")
            or loan_sizing.get("recommended_cr")
            or 0.0
        )
        if coll_limit > 0 and rec_cr > 0:
            security_cover = round(coll_limit / rec_cr, 2)

    # FIX: CCC — default 0 cleanly
    ccc = float(
        wc_analysis.get("latest_ccc")
        or wc_analysis.get("avg_ccc")
        or 0.0
    )

    return {
        "company_name":      comp.get("name", "The Company"),
        "sector":            comp.get("sector", "manufacturing"),
        "years":             fin.get("years", ["FY2022", "FY2023", "FY2024"]),
        "promoters":         financial_data.get("promoters", []),
        "promoter_pct":      financial_data.get("shareholding_pattern", {})
                             .get("promoter_total_pct", 0),

        # Scorecard
        "decision":          scorecard.get("decision", "REJECT"),
        "grade":             scorecard.get("risk_grade", "D"),
        "score":             scorecard.get("normalised_score", 0),
        "primary_trigger":   scorecard.get("primary_rejection_trigger", ""),
        "counter_factual":   scorecard.get("counter_factual", ""),

        # Financials
        "dscr":              float(wc_analysis.get("latest_dscr") or 0.0),
        "de_ratio":          float(wc_analysis.get("latest_de_ratio") or 0.0),
        "revenue_cagr":      revenue_cagr,
        "ebitda_margins":    ebitda_margins,
        "ccc":               ccc,
        "tnw_latest":        latest(bs, "tangible_net_worth"),
        "total_debt_latest": latest(bs, "total_debt"),

        # Loan
        "requested_cr":      float(lr.get("total_requested_cr", 0)),
        "recommended_cr":    float(
                                 loan_sizing.get("recommendation", {}).get("recommended_cr")
                                 or loan_sizing.get("recommended_cr")
                                 or 0
                             ),
        "rate":              float(
                                 loan_sizing.get("rate", {}).get("recommended_rate_pct")
                                 or loan_sizing.get("recommended_rate_pct")
                                 or 0
                             ),
        "security_cover":    security_cover,  # FIX: actual ratio e.g. 1.96x

        # Research
        "pledge_pct":        float(rp_analysis.get("total_promoter_pledged_pct") or 0),
        "lit_label":         lit_summary.get("aggregate_label", "UNKNOWN"),
        "knockout":          lit_summary.get("knockout", False),

        # Insights (field observations)
        "insights":          insights,
        "has_insights":      insights is not None,
        "insights_delta":    insights.get("total_delta", 0) if insights else 0,
    }