"""
cam/llm_narrator.py
─────────────────────────────────────────────────────────────────────────────
LLM Narrative Generator for Credit Appraisal Memos.

Uses Claude API to generate the PROSE sections of the CAM.
All numbers, tables, and scores come from deterministic modules —
the LLM only writes the connecting narrative.

CAM Sections generated here:
  1. Executive Summary        (decision rationale + key risks in 3 sentences)
  2. Company Background       (sector context + promoter profile)
  3. Financial Analysis       (trend narrative — improving/deteriorating)
  4. Risk Factors & Mitigants (structured risk register with mitigants)
  5. Recommendation           (final credit recommendation paragraph)

Sections NOT generated by LLM (populated by doc_builder.py from data):
  - Cover page (pure data)
  - Financial tables (deterministic)
  - Five Cs scorecard table (deterministic)
  - Loan terms table (deterministic)
  - Audit trail (deterministic)

DEMO FALLBACK: If Anthropic API is unavailable, every section has a
deterministic template that produces sensible output from the data alone.
─────────────────────────────────────────────────────────────────────────────
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

try:
    import httpx
    HTTPX_AVAILABLE = True
except ImportError:
    HTTPX_AVAILABLE = False

# Anthropic API constants
ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
ANTHROPIC_MODEL   = "claude-sonnet-4-20250514"
ANTHROPIC_VERSION = "2023-06-01"


# ── Output structure ──────────────────────────────────────────────────────────

@dataclass
class CAMNarrative:
    """All narrative sections of the CAM, ready for doc_builder."""
    executive_summary:   str
    company_background:  str
    financial_analysis:  str
    risk_factors:        str     # Structured as numbered list text
    recommendation:      str
    model_used:          str     # "claude" | "template_fallback"
    warnings:            list[str] = field(default_factory=list)


# ── Main Generation Function ──────────────────────────────────────────────────

async def generate_cam_narrative(
    financial_data: dict,
    scorecard:      dict,
    loan_sizing:    dict,
    wc_analysis:    dict,
    rp_analysis:    dict,
    research_cache: dict,
    lit_summary:    dict,
) -> CAMNarrative:
    """
    Generate all narrative sections for the CAM.
    Tries Claude API first; falls back to deterministic templates.
    """
    logger.info("Generating CAM narrative (model=%s)", ANTHROPIC_MODEL)

    ctx = _build_context(
        financial_data, scorecard, loan_sizing,
        wc_analysis, rp_analysis, research_cache, lit_summary
    )

    if HTTPX_AVAILABLE:
        try:
            sections = await _call_claude_api(ctx)
            return CAMNarrative(model_used="claude", **sections)
        except Exception as e:
            logger.warning("Claude API failed (%s) — using template fallback", e)

    # Deterministic template fallback
    sections  = _template_fallback(ctx)
    warnings  = ["Claude API unavailable — narrative generated from deterministic templates"]
    return CAMNarrative(model_used="template_fallback", warnings=warnings, **sections)


# ── Claude API Calls ──────────────────────────────────────────────────────────

async def _call_claude_api(ctx: dict) -> dict:
    """
    Call Claude API for all 5 sections in a single well-structured prompt.
    Uses XML tags to extract each section reliably.
    """
    company   = ctx["company_name"]
    decision  = ctx["decision"]
    grade     = ctx["grade"]
    score     = ctx["score"]
    dscr      = ctx["dscr"]
    de        = ctx["de_ratio"]
    pledge    = ctx["pledge_pct"]
    lit_label = ctx["lit_label"]
    knockout  = ctx["knockout"]
    rec_cr    = ctx["recommended_cr"]
    rate      = ctx["rate"]
    sector    = ctx["sector"]
    ebitda_margins = ctx["ebitda_margins"]
    revenue_cagr   = ctx["revenue_cagr"]
    primary_trigger = ctx["primary_trigger"]
    counter_factual = ctx["counter_factual"]

    prompt = f"""You are a senior Indian credit analyst writing a Credit Appraisal Memorandum (CAM) 
for submission to the credit committee of an NBFC. Write in formal, precise banking English.
Use Indian financial conventions (lakhs/crores, RBI guidelines, IBC references).

Company: {company}
Sector: {sector}
Score: {score}/100 | Grade: {grade} | Decision: {decision}
DSCR: {dscr:.2f}x | D/E: {de:.2f}x | Promoter Pledge: {pledge:.1f}%
EBITDA Margins (FY2022→FY2024): {ebitda_margins}
Revenue CAGR (3yr): {revenue_cagr:.1f}%
Litigation: {lit_label} | Knockout: {knockout}
Primary rejection trigger: {primary_trigger}
Recommended: ₹{rec_cr:.1f} Cr @ {rate:.2f}% p.a.
Counter-factual: {counter_factual}

Generate exactly 5 sections wrapped in XML tags. Each section: 3-5 sentences, formal tone.
Be specific with numbers. Do not invent figures not given above.

<executive_summary>
3 sentences: (1) overall credit assessment and grade, (2) key strength, (3) primary risk/reason for decision.
</executive_summary>

<company_background>
3-4 sentences on the company's business, sector standing, and promoter profile based on the data given.
</company_background>

<financial_analysis>
4-5 sentences on financial performance trends: revenue growth, EBITDA margin trajectory, 
debt levels, and working capital — citing the specific numbers given.
</financial_analysis>

<risk_factors>
Write exactly 4 numbered risk factors with their mitigants in this format:
1. [Risk]: [description]. Mitigant: [mitigant].
2. [Risk]: [description]. Mitigant: [mitigant].
3. [Risk]: [description]. Mitigant: [mitigant].
4. [Risk]: [description]. Mitigant: [mitigant].
</risk_factors>

<recommendation>
3-4 sentences: state the credit committee recommendation, the decision rationale, 
key conditions precedent, and the monitoring requirements post-sanction.
</recommendation>"""

    async with httpx.AsyncClient(timeout=30) as client:
        response = await client.post(
            ANTHROPIC_API_URL,
            headers={
                "Content-Type":         "application/json",
                "anthropic-version":    ANTHROPIC_VERSION,
            },
            json={
                "model":      ANTHROPIC_MODEL,
                "max_tokens": 1500,
                "messages": [{"role": "user", "content": prompt}],
            },
        )
        response.raise_for_status()
        data = response.json()

    raw_text = data["content"][0]["text"]
    return _parse_claude_response(raw_text)


def _parse_claude_response(text: str) -> dict:
    """Extract sections from Claude's XML-tagged response."""
    import re

    def extract(tag: str) -> str:
        pattern = rf"<{tag}>(.*?)</{tag}>"
        match   = re.search(pattern, text, re.DOTALL)
        return match.group(1).strip() if match else ""

    return {
        "executive_summary":  extract("executive_summary"),
        "company_background": extract("company_background"),
        "financial_analysis": extract("financial_analysis"),
        "risk_factors":       extract("risk_factors"),
        "recommendation":     extract("recommendation"),
    }


# ── Template Fallback ─────────────────────────────────────────────────────────

def _template_fallback(ctx: dict) -> dict:
    """
    Deterministic narrative templates — used when Claude API is unavailable.
    Produces professional, data-accurate text from the context dict.
    """
    c      = ctx["company_name"]
    sec    = ctx["sector"]
    grade  = ctx["grade"]
    score  = ctx["score"]
    dec    = ctx["decision"]
    dscr   = ctx["dscr"]
    de     = ctx["de_ratio"]
    pledge = ctx["pledge_pct"]
    rec    = ctx["recommended_cr"]
    rate   = ctx["rate"]
    lit    = ctx["lit_label"]
    years  = ctx["years"]
    rev_cagr  = ctx["revenue_cagr"]
    ebitda_m  = ctx["ebitda_margins"]
    trigger   = ctx["primary_trigger"]
    counter   = ctx["counter_factual"]
    promoters = ctx["promoters"]
    tnw_latest = ctx["tnw_latest"]
    total_debt = ctx["total_debt_latest"]

    executive_summary = (
        f"{c} has been assigned a credit grade of {grade} ({score}/100) on the "
        f"Five Cs scorecard, resulting in a recommendation to {dec} the proposed "
        f"credit facility. "
        f"The company demonstrates {rev_cagr:.1f}% revenue CAGR over {years[0]}–{years[-1]} "
        f"with improving EBITDA margins ({ebitda_m[0]}%→{ebitda_m[-1]}%), supported by "
        f"tangible net worth of ₹{tnw_latest:.0f}L and first-charge security. "
        f"The primary constraint is {trigger[:100]}."
    )

    promo_names = " and ".join(p["name"] for p in promoters)
    company_background = (
        f"{c} is a {sec}-sector company promoted by {promo_names}, with operations "
        f"established since its incorporation. "
        f"The promoters hold {ctx['promoter_pct']:.1f}% equity stake, of which "
        f"{pledge:.1f}% is pledged to lenders as security for existing facilities. "
        f"The company's primary banking relationship is with its existing lenders, "
        f"and it holds an external credit rating from its rating agency."
    )

    financial_analysis = (
        f"{c} has grown revenue at a CAGR of {rev_cagr:.1f}% over {years[0]}–{years[-1]}, "
        f"with EBITDA margins improving from {ebitda_m[0]:.1f}% to {ebitda_m[-1]:.1f}%. "
        f"Total debt stood at ₹{total_debt:.0f}L against tangible net worth of "
        f"₹{tnw_latest:.0f}L, yielding a D/E ratio of {de:.2f}x as at {years[-1]}. "
        f"Debt Service Coverage Ratio (DSCR) of {dscr:.2f}x in {years[-1]} is "
        f"{'below' if dscr < 1.30 else 'at'} the minimum threshold of 1.30x, "
        f"indicating {'stressed' if dscr < 1.30 else 'adequate'} debt servicing capacity. "
        f"Working capital intensity is elevated with Cash Conversion Cycle of "
        f"{ctx['ccc']:.0f} days."
    )

    risk_factors = (
        f"1. Litigation Risk ({lit}): {trigger[:120]}. "
        f"Mitigant: {counter[:100]}.\n"
        f"2. Debt Service Risk: DSCR of {dscr:.2f}x is below the minimum threshold of 1.30x, "
        f"leaving limited buffer for revenue/margin stress. "
        f"Mitigant: Proposed escrow of 1 quarter's debt service as condition precedent.\n"
        f"3. Promoter Pledge Concentration: {pledge:.1f}% of promoter holding is pledged, "
        f"creating margin call risk in the event of stock price decline. "
        f"Mitigant: Pledge release schedule to be agreed as a covenant within 24 months.\n"
        f"4. Working Capital Pressure: Cash Conversion Cycle of {ctx['ccc']:.0f} days indicates "
        f"elevated debtor and inventory holding. "
        f"Mitigant: Monthly stock/debtor statements with drawing power computation."
    )

    if dec == "REJECT":
        rec_text = (
            f"The Credit Committee is recommended to DECLINE the proposed facility of "
            f"₹{ctx['requested_cr']:.1f} Cr from {c} at this time. "
            f"The primary basis for decline is: {trigger[:120]}. "
            f"The application may be reconsidered subject to: {counter[:150]}. "
            f"No credit facility should be extended until the NCLT proceedings are fully resolved."
        )
    elif dec == "PARTIAL":
        rec_text = (
            f"The Credit Committee is recommended to consider a PARTIAL approval of "
            f"₹{rec:.1f} Cr (against the requested ₹{ctx['requested_cr']:.1f} Cr) "
            f"@ {rate:.2f}% p.a. for {c}, subject to satisfactory resolution of "
            f"pending conditions precedent. "
            f"Disbursement to be withheld pending clearance of: {trigger[:100]}. "
            f"Post-sanction monitoring: quarterly DSCR certification, monthly stock statements, "
            f"and annual pledge reduction milestones."
        )
    else:
        rec_text = (
            f"The Credit Committee is recommended to APPROVE the facility of "
            f"₹{rec:.1f} Cr @ {rate:.2f}% p.a. for {c} (Grade {grade}). "
            f"The facility is adequately secured with security cover of "
            f"{ctx['security_cover']:.2f}x. "
            f"Conditions precedent: satisfactory legal search, executed security documents, "
            f"and insurance endorsement in lender's favour. "
            f"Post-sanction monitoring: quarterly DSCR review and annual financial audit."
        )

    return {
        "executive_summary":  executive_summary,
        "company_background": company_background,
        "financial_analysis": financial_analysis,
        "risk_factors":       risk_factors,
        "recommendation":     rec_text,
    }


# ── Context Builder ───────────────────────────────────────────────────────────

def _build_context(
    financial_data: dict,
    scorecard:      dict,
    loan_sizing:    dict,
    wc_analysis:    dict,
    rp_analysis:    dict,
    research_cache: dict,
    lit_summary:    dict,
) -> dict:
    """Flatten all inputs into a single context dict for prompt / template."""
    fin    = financial_data.get("financials", {})
    pnl    = fin.get("profit_and_loss", {})
    bs     = fin.get("balance_sheet", {})
    comp   = financial_data.get("company", {})
    lr     = financial_data.get("loan_request", {})

    def latest(d: dict, key: str, fb=0.0):
        v = d.get(key, fb)
        return float(v[-1]) if isinstance(v, list) and v else float(v or fb)

    ebitda_margins_raw = pnl.get("ebitda_margin_pct", [])
    ebitda_margins     = [round(float(m), 1) for m in ebitda_margins_raw]

    return {
        "company_name":    comp.get("name", "The Company"),
        "sector":          comp.get("sector", "manufacturing"),
        "years":           fin.get("years", ["FY2022", "FY2023", "FY2024"]),
        "promoters":       financial_data.get("promoters", []),
        "promoter_pct":    financial_data.get("shareholding_pattern", {}).get("promoter_total_pct", 0),

        # Scorecard
        "decision":        scorecard.get("decision", "REJECT"),
        "grade":           scorecard.get("risk_grade", "D"),
        "score":           scorecard.get("normalised_score", 0),
        "primary_trigger": scorecard.get("primary_rejection_trigger", ""),
        "counter_factual": scorecard.get("counter_factual", ""),

        # Financials
        "dscr":            wc_analysis.get("latest_dscr", 0.0),
        "de_ratio":        wc_analysis.get("latest_de_ratio", 0.0),
        "revenue_cagr":    wc_analysis.get("revenue_cagr_pct", 0.0),
        "ebitda_margins":  ebitda_margins,
        "ccc":             wc_analysis.get("latest_ccc", 0.0),
        "tnw_latest":      latest(bs, "tangible_net_worth"),
        "total_debt_latest": latest(bs, "total_debt"),

        # Loan
        "requested_cr":    float(lr.get("total_requested_cr", 0)),
        "recommended_cr":  loan_sizing.get("recommendation", {}).get("recommended_cr", 0),
        "rate":            loan_sizing.get("rate", {}).get("recommended_rate_pct", 0),
        "security_cover":  scorecard.get("contributions", {}).get("security_cover", {}).get("pct", 0) / 100,

        # Research
        "pledge_pct":      rp_analysis.get("total_promoter_pledged_pct", 0),
        "lit_label":       lit_summary.get("aggregate_label", "UNKNOWN"),
        "knockout":        lit_summary.get("knockout", False),
    }